### ISSUE TITLE
Which version for sktime ?

### ISSUE THREAD

**Issue by pnavaro** [StevenGolovkine/FDApy#5]
Dear Steven, i am trying to run the example plot_canadian_weather but i can't install correctly the package. I still get this error

```
$ python
Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:59:12)
[Clang 11.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from FDApy.misc.loader import read_csv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/navaro/PycharmProjects/FDApy/FDApy/misc/loader.py", line 14, in <module>
    from sktime.utils.load_data import load_from_tsfile_to_dataframe
ModuleNotFoundError: No module named 'sktime.utils.load_data'
>>> import sktime
>>> sktime.__version__
'0.6.1'
```

I don't know which version of sktime i need to install. Thanks for your help.

**Comment by StevenGolovkine** [comment]
Dear Pierre

The version 0.3.1 of sktime should work. I'll update the code to be compatible to new version of sktime.
